languages:
  python:
    extensions: [".py"]
  go:
    extensions: [".go"]
  javascript:
    extensions: [".js", ".jsx"]
  typescript:
    extensions: [".ts", ".tsx"]

thresholds:
  complexity: 20
  duplication: 10

ignore_paths:
  - "node_modules/"
  - "vendor/"
  - "tests/"

analyzers:
  complexity:
    function_threshold: 10
    file_threshold: 200
  dependency:
    max_depth: 5
    detect_cycles: true
  patterns:
    enabled_rules: ["singleton", "factory", "god_class"]
