analyzers:
  complexity:
    file_threshold: 200
    function_threshold: 10
  dependency:
    detect_cycles: true
    max_depth: 5
  patterns:
    enabled_rules:
    - singleton
    - factory
    - god_class
ignore_paths:
- node_modules/
- vendor/
- tests/
languages:
  go:
    extensions:
    - .go
  javascript:
    extensions:
    - .js
    - .jsx
  python:
    extensions:
    - .py
  typescript:
    extensions:
    - .ts
    - .tsx
llm:
  api_key: ${OPENAI_API_KEY}
  enabled: true
  model: gpt-4
  provider: openai
  retries: 3
  temperature: 0.0
  timeout: 60
snapshot:
  compression:
    enabled: true
    exclude_patterns:
    - '*.test.go'
    - '*_test.py'
  formats:
  - json
  - markdown
  markdown:
    include_source_code: false
    max_code_lines: 20
    template: default_report
  output_dir: .codesage/snapshots
  versioning:
    enabled: true
    max_versions: 10
    retention_days: 30
thresholds:
  complexity: 20
  duplication: 10
org:
  projects:
    - id: codesage
      name: codesage
      path: .
      snapshot_path: v1.json
