from __future__ import annotations
from typing import List
from codesage.report.summary_models import ReportProjectSummary, ReportFileSummary


def render_markdown(project_summary: ReportProjectSummary, files: List[ReportFileSummary], *, max_files: int = 20) -> str:
    # 1. Project Overview
    report_parts = [
        "# CodeSnapAI Project Analysis Report",
        "## Project Overview",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Total Files | {project_summary.total_files} |",
        f"| High Risk Files | {project_summary.high_risk_files} |",
        f"| Medium Risk Files | {project_summary.medium_risk_files} |",
        f"| Low Risk Files | {project_summary.low_risk_files} |",
        f"| Total Issues | {project_summary.total_issues} |",
        f"| Error Issues | {project_summary.error_issues} |",
        f"| Warning Issues | {project_summary.warning_issues} |",
        f"| Info Issues | {project_summary.info_issues} |",
        "",
    ]

    # 2. Top N Risky Files
    report_parts.extend([
        "## Top Risky Files",
        "| File Path | Risk Score | Total Issues | Error Issues | Top Issue Rules |",
        "| --- | --- | --- | --- | --- |",
    ])

    risky_files_sorted = sorted(files, key=lambda f: f.risk_score, reverse=True)
    for file in risky_files_sorted[:max_files]:
        top_rules = ", ".join(file.top_issue_rules)
        report_parts.append(f"| {file.path} | {file.risk_score:.2f} | {file.issues_total} | {file.issues_error} | {top_rules} |")
    report_parts.append("")

    # 3. Top Rules
    report_parts.extend([
        "## Top Rules Triggered",
        "| Rule ID |",
        "| --- |",
    ])
    for rule in project_summary.top_rules:
        report_parts.append(f"| {rule} |")
    report_parts.append("")

    # 4. Footer
    report_parts.append("---")
    report_parts.append("Generated by [CodeSnapAI](https://github.com/example/codesnapai)")

    return "\n".join(report_parts)
